# Generated by Django 6.0 on 2025-12-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='abstract_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_presenter',
            field=models.BooleanField(default=False),
        ),
    ]
