# Generated by Django 5.2.9 on 2026-01-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_id_alter_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accompanying_persons',
            field=models.IntegerField(default=0),
        ),
    ]
