# Generated by Django 6.0.5 on 2026-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_registration_add_presentation_and_payment_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='beverage_choice',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='food_preference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='oral_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='poster_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
