# Generated by Django 6.0.5 on 2026-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_missing_registration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='workshop_id',
            field=models.PositiveIntegerField(choices=[(1, 'Workshop 1 - XRD & XRF Characterization'), (2, 'Workshop 2 - Synchrotron-Based Techniques for Materials Characterization')], default=1),
        ),
    ]
