# Generated by Django 5.2.14 on 2026-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registration_beverage_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='workshop_id',
            field=models.PositiveIntegerField(choices=[(1, 'Workshop 1 - XRD & XRF Characterization'), (2, 'Workshop 2 - Synchrotron-Based Techniques for Materials Characterization')], default=1),
        ),
    ]
