# Generated by Django 5.2.14 on 2026-05-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registration_oral_presentation_and_more'),
        ('core', '0008_add_missing_registration_fields'),
        ('core', '0009_alter_workshopregistration_workshop_id'),
    ]

    operations = [
    ]
