# Generated by Django 5.2.14 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_merge_20260516_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopregistration",
            name="registration_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
