# Generated by Django 5.2.14 on 2026-05-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_customuser_id_alter_registration_id_and_more"),
        ("core", "0011_workshop_registration_code"),
    ]

    operations = [
    ]
