# Generated by Django 6.0.6 on 2026-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_merge_20260522_0000"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="certificate_override",
            field=models.BooleanField(
                default=False,
                help_text="⚠️ TESTING ONLY — set to True only for test registrations. Always reset to False after testing. Never enable for real participants.",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workshopregistration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
