# Generated by Django 6.0.6 on 2026-06-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_certificate_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="certificate_blob",
            field=models.BinaryField(
                blank=True, help_text="Pre-generated certificate PNG bytes.", null=True
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="certificate_template_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="MD5 hash of template at generation time.",
                max_length=32,
                null=True,
            ),
        ),
    ]
